### ISSUE TITLE
ros command cannot be recognized in UBUNTU 16.04

### ISSUE THREAD

**Issue by hityrj** [taketwo/vim-ros#18]
FIrst of all, vim-ros is a very useful plugin for vim.
vim-ros was successfully installed and run in Ubuntu 14.04 on my computer.
Currently, I installed this plugin in Ubuntu 16.04 by following the same steps I have done for Ubuntu 14.04.
However, even though the installation was successful, the ros commands, for example Rosed, Roscd, cannot be recognized in VIM.
Is this the compatibility problem? 
Or some additional steps are needed for UBUNTU 16.04.

Thanks for your help.

**Comment by taketwo** [comment]
Hi, I'm glad that you find this plugin useful.

Could it be that the problem is with Python version? What does `vim --version` say?

**Comment by hityrj** [comment]
Python version:  Python 2.7.12
Output of vim --version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm

**Comment by taketwo** [comment]
I think the problem is that your version of Vim is compiled with Python 3 support. ROS, however, is still Python 2 only. So I guess the plugin (which runs in Vim and thus in Python 3 environment) fails to load ROS packages that are Python 2.

On Ubuntu 16.04 there is a `vim-nox-py2` package in `apt-get`. Try to install this one to get Vim compiled with old Python 2 support.

**Comment by hityrj** [comment]
Wow great, thank you very much for your help.
For Ubuntu 16.04, `vim-nox-py2` is necessary for `vim-ros` plugin:
```
sudo apt-get update
sudo apt-get install vim-nox-py2
```
