### ISSUE TITLE
Using vim-plug lazy loading

### ISSUE THREAD

**Issue by pylipp** [taketwo/vim-ros#20]
Hej, 
do you see a way to take advantage of vim-plug's lazy loading? F.i. to load vim-ros only when I'm inside a workspace. This would require a script to look for appropriate ROS environments variables or for the `.catkin_workspace` file in a parent directory. 

However, thanks for creating this plugin. Helps my workflow a lot :)

**Comment by taketwo** [comment]
Never thought about this. On my machine loading the plugin during Vim startup amounts to only 9 ms. It creates an autocommand that is executed when new buffers are opened. This command is a simple `rospkg.get_package_name(vim.eval('a:filename'))`, which succeeds only if the file belongs to a ROS package.

So yes, there is an overhead, but it's tiny (at least from my perspective). However, if it bothers you, we can add a check somewhere early in `plugin/ros.vim` that figures out if the current working directory is in a workspace and blocks plugin loading if it's not. This will save time on every succeeding buffer opening. (This solution won't use `vim-plug` lazy loading, don't think it can bring any additional benefits.)

**Comment by pylipp** [comment]
The startup time is neglectable indeed, and adding a check in `plugin/ros.vim` sounds a bit cumbersome. So I'll close this for now.
