### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by paul-mesnilgrente** [taketwo/vim-ros#21]
Hello,

I tried to install your plugin with pathogen but it does not work. Here what I did:
```bash
cd ~/.vim/bundle
git clone https://github.com/taketwo/vim-ros
cd ~/catkin_ws
rosed pkg my_file
```

There I tried to run the command :Rosed but vim does not find it.

Do you know why? Your package is very interesting.

**Comment by taketwo** [comment]
This plugin needs  Vim version 7 or above, compiled with Python support. Can you please check that this requirement is satisfied?

**Comment by paul-mesnilgrente** [comment]
Here what is showing the command `sudo apt-cache show vim`
```text
Version: 2:7.4.1689-3ubuntu1.2
Depends: vim-common (= 2:7.4.1689-3ubuntu1.2), vim-runtime (= 2:7.4.1689-3ubuntu1.2), libacl1 (>= 2.2.51-8), libc6 (>= 2.15), libgpm2 (>= 1.20.4), libpython3.5 (>= 3.5.0~b1), libselinux1 (>= 1.32), libtin
fo5 (>= 6)
```

That is the package that I have installed, is it answering your question?

**Comment by taketwo** [comment]
Ah, you probably have default Vim in Ubuntu 16.04. Please see #18.
A note to self: add this info to the readme.

**Comment by paul-mesnilgrente** [comment]
That was the problem, sorry, I didn't see this issue.
**To solve this issue**
```bash
sudo apt install vim-nox-py2
```

Thank you.

**Comment by Dheeru97** [comment]
sudo apt install vim-nox-py2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vim-nox-py2 : Depends: vim-common (= 2:7.4.1689-3ubuntu1) but 2:7.4.1689-3ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by taketwo** [comment]
Try to add `-f` flag to the command, i.e. `sudo apt -f install vim-nox-py2`.

**Comment by taketwo** [comment]
See #25.
