### ISSUE TITLE
Can't seem to get this package to work

### ISSUE THREAD

**Issue by ManuelMeraz** [taketwo/vim-ros#23]
I'm on Ubuntu 14.04 so my default python is 2.7.6

I use pathogen for my vim plugins and I cloned your repository into `~/.vim/bundle`

I added these options to my .vimrc:
```
let g:ros_make = 'current'
let g:ros_build_system = 'rosbuild'
```
Here is my output for `vim --version`

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 23 2017 14:01:38)
Included patches: 1-313, 315-662
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu -lpython3.4m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib    
```

None of the commands like :Rosed work 

Thank you!

**Comment by taketwo** [comment]
Hi, let's first figure out if the plugin is picked up by Pathogen and is loaded. Please start vim (in any directory, does not have to be ROS package) and execute command `:echo g:loaded_ros`. What is the output?

**Comment by ManuelMeraz** [comment]
It looks like I'm getting an error

```
E121: Undefined variable: g:loaded_ros
E15: Invalid expression: g:loaded_ros
```

Here's my vimrc. Added the .txt extension so github would allow me to attach it. 
[vimrc.txt](https://github.com/taketwo/vim-ros/files/1109376/vimrc.txt)

**Comment by taketwo** [comment]
Clearly, the plugin is not loaded, so this is an issue with your Pathogen setup. Unfortunately it's been a very very long time since I stopped using this plugin manager, so I can not say what exactly you are doing wrong.

I see in your `.vimrc` you manually add the path to "jshint2.vim". I suppose if you do the same for "vim-ros" you will get it loaded and working. But this is not a proper fix, of course.

**Comment by ManuelMeraz** [comment]
So I added `vim-ros` to my vimrc by doing:

`set runtimepath+=~/.vim/bundle/vim-ros/`

Then I found out about `:scriptnames`, which shows all .vim scripts running. I then decided to comment out manually adding `vim-ros` to the `runtimepath`. It still showed the script running. You can  see that it is commented out on the left pane which has my vimrc loaded, which I made sure to save after commenting it out. The right pane is right after I called `:scriptnames:` in vim.

![vim](https://user-images.githubusercontent.com/10673962/27689143-731438e2-5c9a-11e7-9a80-ac41bc561da4.png)

These are the values for the variable `vimruntime`, which has the `~/.vim/bundle/vim-ros` directory in there. So it looks like it detects it. 
![runtimepath](https://user-images.githubusercontent.com/10673962/27689212-c19e64a6-5c9a-11e7-85d8-1a2ea6dc688d.png)

What do you think?

**Comment by taketwo** [comment]
What happens if you run `python -c "import rospkg"` in terminal?

**Comment by ManuelMeraz** [comment]
Looks like it runs successfully, since the command returns a 0
```
manny@dixy:~$ python -c "import rospkg"
manny@dixy:~$ echo $?
0
```

**Comment by taketwo** [comment]
Oh, sorry. The problem was clear already from your issue description, but I did not pay enough attention. Your `vim` is compiled without Python2 (`-python`) rather with Python3 (`+python3`). Unfortunately, ROS is compatible only with Python2. This means that this plugin (which runs as Python3 because it belongs to `vim`) can not use any of the ROS python packages, and therefore can not do anything useful. For possible solution see #18.

**Comment by ManuelMeraz** [comment]
I guess I forgot to mention, but I already read that issue and installed `vim-nox-py2` already.

**Comment by taketwo** [comment]
But the output of `vim --version` that you posted says that you have `+python3` version.

**Comment by ManuelMeraz** [comment]
I do have python3 installed, but python 2.7.6 runs if I call python. To use python3 I have to explicitly call python3.

**Comment by taketwo** [comment]
Your system's default Python version does not matter. What matters is the version of Python which Vim uses. Try to run the following command in Vim:

```
:py import platform; print(platform.python_version())
```

**Comment by ManuelMeraz** [comment]
![vim-pyversion](https://user-images.githubusercontent.com/10673962/27691670-ff75cdb2-5ca1-11e7-8cbb-8c4d972383fa.png)

**Comment by taketwo** [comment]
Oh, right. Exactly! You even need to call `py3` I suppose.

**Comment by ManuelMeraz** [comment]
I see I understand the issue now. The `+python3` means it utilizes `python3` over `python`. It looks like `vim-nox-py2` hasn't done anything, I'll see if I can find something out. The command worked with `python3` by the way.

**Comment by taketwo** [comment]
I committed an update (045d319ef22) that prints an error message when the plugin is loaded in Vim compiled without `python2` support.
