### ISSUE TITLE
unable to install vim

### ISSUE THREAD

**Issue by Dheeru97** [taketwo/vim-ros#25]
sudo apt install vim-nox-py2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vim-nox-py2 : Depends: vim-common (= 2:7.4.1689-3ubuntu1) but 2:7.4.1689-3ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by taketwo** [comment]
This issue has nothing to do with the plugin. Please ask at more relevant places (e.g. ubuntu forums) or use Google to find a solution.

That being said, you can try to add `-f` flag to the command, i.e. `sudo apt -f install vim-nox-py2`, maybe will help.
