### ISSUE TITLE
Unknown function: ros#BufInit

### ISSUE THREAD

**Issue by rivertam** [taketwo/vim-ros#26]
Hey there. Just installed the plugin using neovim and when I open the directory, I get an error. When I run `:copen` (which I think is how you see that initial error? But maybe it's another error. Also, if anyone can tell me how to enter visual mode in this buffer so I can copy, that would be great; everything below is rewritten by hand) I get the following:

```
Error detected while processing function <SNR>105_Detect[5]..provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
NvimError: Vim(return):E117: Unknown function: ros#BufInit
```

I've also taken a screenshot because I figured maybe visual context might help.

![2017-31-10_17-31-15](https://user-images.githubusercontent.com/4165105/30253180-e5354564-964d-11e7-8b3d-f72d07ce1724.png)

I'm not even sure if neovim is supported, but I figure it shouldn't be too off. I know there are plenty of python2 plugins for neovim.

My `init.vim` can be found [here](https://raw.githubusercontent.com/rivertam/.files/38d83f90ec1c55233b6fbbfebba161b8f959c7cc/init.vim)

`nvim --version` output:

```
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/build/config -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/src -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-XHx5my/neovim-0.2.0ubuntu1+git201709070740+3629+26~ubuntu16.04.1/build/include
Compiled by buildd@lcy01-24

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by taketwo** [comment]
> I'm not even sure if neovim is supported, but I figure it shouldn't be too off.

Switching to _neovim_ has been on my TODO list for a while now. Unfortunately, I haven't even tried it yet and I am still on _vim_. From what I've heard it indeed shouldn't be too off and _vim_ plugins should work without glitch. Apparently, not the case with this plugin. But I hope it's some small issue, maybe one of the version checks fail on initialization. I'll have a look at this eventually, but do not know when, sorry.

**Comment by rivertam** [comment]
=/ Okay, thanks for your time.

**Comment by rivertam** [comment]
@taketwo For better or for worse, I'm pretty focused on fixing this issue. Hoping I could get some insight from you, seeing as I don't really know python (and this seems to be an issue internal to python, ironically, as far as I can tell)

I believe the message above is actually from my `:copen` command, which is failing because `ros#BufInit` is never defined because the script that defines it fails before it can get defined, so I'm trying to figure out why that script fails. I don't really know how to debug, so I'm just using `vim.command('echo "nonsense"')`, but I put relevant echos in the following locations:

```python
# in plugin/vimp/__init__.py

import vim

def escape():
  # ... unchanged
  pass # not really, just trying to make this roughly valid

vim.command('echo "nothing"')

from variables import _Variables

vim.command('echo "getting"')
```

So here, "nothing" is getting echoed, but "getting" is not, so I figured the error must be thrown inside `plugin/vimp/variables.py`.

However, I put a `vim.command('echo "here"')` just after `import vim` in `plugin/vimp/variables.py`, and that echo does not seem to be occurring.

I could be doing something very stupid, like putting it in the wrong file or interpreting the output differently, so anything you see that I'm doing wrong here would be appreciated, but I don't understand exactly what's wrong. The `import` statement itself seems to be failing (unless it's `import vim`, which I doubt). I also thought it might have to do with the `#!/usr/bin/env python \n # encoding: utf-8` missing from `variables.py`, but no dice.

Any insight would be appreciated. I definitely understand that you're busy, but if you could even just point out any suspicions you have, I'd like to look into it.

**Comment by rivertam** [comment]
Oh man, after all that I just tried adding `let g:ros_use_python_version = 2` to my `init.vim`, and that seems to have done it. Maybe I'm using a version of python3 that's incompatible with the code? I'm not sure why neovim would make a difference here. The README implies we should use 2, but the autoload defaults to 3. Not sure I understand, but this seems to solve my issues.

**Comment by taketwo** [comment]
Thanks for debugging this. The code related to [`g:ros_use_python_version`](https://github.com/taketwo/vim-ros/blob/045d319ef2270361fa0e228f358a8fe1a320d7d0/autoload/ros.vim#L12-L28) makes no sense! I derived (read copy/pasted) them from the `vim-rails` codebase in the early days of this plugin. Only later I realized that since ROS is not Python3 compatible, the plugin also can not be compatible with Python3. Apparently, by that time I totally forgot about this code block. It makes no problem in _vim_, because _vim_ always has either `py2` or `py3`, not both. Contrary, _neovim_ has both, and due to the logic implemented in the referenced code, we end up using Python3, which, again, does not make sense for ROS.

I will push an update fixing this soon.

**Comment by rivertam** [comment]
Sweet. Totally unrelated, but I'm working on a deoplete integration.

**Comment by taketwo** [comment]
You can now remove `let g:ros_use_python_version = 2` from your init file. Thanks again for reporting and debugging.

**Comment by rivertam** [comment]
ah nvm I thought this provided autocompletion for C++ but it doesn't look like it, which is totally fair because a C++ backend properly configured should be able to do that.

**Comment by rivertam** [comment]
Thanks!

**Comment by taketwo** [comment]
> ah nvm I thought this provided autocompletion for C++ but it doesn't look like it, which is totally fair because a C++ backend properly configured should be able to do that.

I recommend YouCompleteMe. Enable compilation database export when you build your catkin workspace and use something like [this](https://github.com/taketwo/mcf/blob/master/misc/.ycm_extra_conf.py) as your YCM config file to discover the database.

**Comment by rivertam** [comment]
Thanks @taketwo for taking the time to help me with this. I switched to YCM for C/C++, and it seems catkin actually generateed a nice .ycm_extra_conf.py for me, which is awesome, but how do I "enable compilation database export"? I tried it with `catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=1` but I think that's something else.

**Comment by taketwo** [comment]
> but how do I "enable compilation database export"? I tried it with `catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=1` but I think that's something else.

That's exactly that. If this works correctly, you should get a file named `compile_commands.json` in the build folder of each of your packages (i.e. in `$ROS_WORKSPACE_PATH/build/package_name/`). These files need to be picked up by YCM.

**Comment by rivertam** [comment]
Okay, thanks so much. I'll do my best from here. =)
