### ISSUE TITLE
Not working albeit installed

### ISSUE THREAD

**Issue by codestumbler** [taketwo/vim-ros#27]
Hi all
I have vim 2.7.12 with YCM working for C++. Installing vim-ros with vundle seems to have worked (it appears according to :PluginList). However, I'm getting no suggestions (Putting the semantic triggers into .vimrc had no effect. ) and  :YcmDiag displays errors for all ros objects. 
What could I have done wrong? Thanks already for any response!

**Comment by taketwo** [comment]
This plugin does nothing to configure YCM. It is the user's responsibility to make sure that the compilation database is generated and can be discovered by YCM.

**Comment by codestumbler** [comment]
Thanks for you answer! Adapting the CMakeLists.txt to create the proper compilation database did it.
