### ISSUE TITLE
Disabling ros.vim: Vim with +python is required 

### ISSUE THREAD

**Issue by pitagorinhas** [taketwo/vim-ros#34]
after i instaled the plugin this message prompt 
please can you help me ?

**Comment by khssnv** [comment]
Check [Installation](https://github.com/taketwo/vim-ros#installation), your error means you need vim built with `python2`. You can check yours like this:
```console
user@pc:~$ vim --version | grep python
+comments          +libcall           +python            +vreplace
+conceal           +linebreak         -python3           +wildignore
```
If you have `-python` instead of `+python` it is a source of the error.

**Comment by pitagorinhas** [comment]
> Check [Installation](https://github.com/taketwo/vim-ros#installation), your error means you need vim built with `python2`. You can check yours like this:
> 
> ```
> user@pc:~$ vim --version | grep python
> +comments          +libcall           +python            +vreplace
> +conceal           +linebreak         -python3           +wildignore
> ```
> 
> If you have `-python` instead of `+python` it is a source of the error.

yeah i dont have it but i also installed vim gtk and i am not able to install nox-py-2 don't know what to do

**Comment by khssnv** [comment]
Actually I have a problem too. I've asked about `python3` support in #35. Probably you have vim built with `+python3` while all newer distributions drops `python2` support.

**Comment by pitagorinhas** [comment]
yes i have python3 i searched everywhere how to be able to compile mi vim
with python2 to get python+ and did no get any concrete answer


Alisher A. Khassanov <notifications@github.com> escreveu no dia terça,
21/04/2020 à(s) 18:14:

**Comment by taketwo** [comment]
ROS still works on Python 2, so no way around using Python 2 in this plugin.

Personally, I've been using Neovim for about a year now and have no issues. In Neovim you can have both Python 2 and Python 3 installed at the same time.

**Comment by pitagorinhas** [comment]
ok i will try neovim

Sergey Alexandrov <notifications@github.com> escreveu no dia terça,
21/04/2020 à(s) 20:05:

**Comment by pitagorinhas** [comment]
> ROS still works on Python 2, so no way around using Python 2 in this plugin.
> 
> Personally, I've been using Neovim for about a year now and have no issues. In Neovim you can have both Python 2 and Python 3 installed at the same time.

It worked, the plugin commands are able to be called however i have to open a new because is not recognizing the #include <ros/ros.h>:
![screenshots1587499462_abr21_21:04:22](https://user-images.githubusercontent.com/62778496/79908805-cace8a80-8413-11ea-8cbc-9afc5f064726.png)

**Comment by taketwo** [comment]
Code completion is outside of the scope of this plugin. Make sure you properly configure your code completer or linter plugin (YCM? ALE?) to let them know where to look for the compilation database of your project.

**Comment by taketwo** [comment]
The plugin requires Python 3 now.
