### ISSUE TITLE
NameError: name 'vim' is not defined

### ISSUE THREAD

**Issue by dongdongbh** [taketwo/vim-ros#40]
I just came to use this plugin, and I'm using `neovim 0.8.0` on `ubuntu 20.04`, after installed this plugin  by `packer`, it throws this error:

```
Error detected while processing function <SNR>52_Detect[1]..provider#python3#Call:                                                                                                            
line   18:                                                                                                                                                                                    
Error invoking 'python_execute' on channel 4 (python3-script-host):                                                                                                                           
Traceback (most recent call last):                                                                                                                                                            
  File "<string>", line 1, in <module>                                                                                                                                                        
NameError: name 'vim' is not defined                                                                                                                                                          
Error detected while processing function <SNR>52_Detect[2]..provider#python3#Call:                                                                                                            
line   18:                                                                                                                                                                                    
Error invoking 'python_execute' on channel 4 (python3-script-host):                                                                                                                           
Traceback (most recent call last):                                                                                                                                                            
  File "<string>", line 1, in <module>                                                                                                                                                        
NameError: name 'package' is not defined
```

I checked the previous issue #36 with the same error, and seems it already merged, but  I still has this error.

**Comment by taketwo** [comment]
Did you follow the instructions in [Installation](https://github.com/taketwo/vim-ros#installation) section? Also, please run :checkhealth in Nvim and post the sections about Python2/3 providers.

**Comment by taketwo** [comment]
From what I can see, you are using system version of Python without a virtual environment. This means that installation of `rospkg` and `catkin-tools` with Pip requires superuser rights. If you used the installation command without running `nvim` as `sudo`, it probably failed. A quick way to check that is to run `$ ls /usr/lib/python3/dist-packages/ | grep rospkg`. If `grep` gives you nothing, try to `$ sudo pip3 install rospkg catkin-tools` in a normal terminal.

**Comment by dongdongbh** [comment]
> From what I can see, you are using system version of Python without a virtual environment. This means that installation of `rospkg` and `catkin-tools` with Pip requires superuser rights. If you used the installation command without running `nvim` as `sudo`, it probably failed. A quick way to check that is to run `$ ls /usr/lib/python3/dist-packages/ | grep rospkg`. If `grep` gives you nothing, try to `$ sudo pip3 install rospkg catkin-tools` in a normal terminal.


seems not that problem
```
$ ls /usr/lib/python3/dist-packages/ | grep rospkg
rospkg
rospkg-1.4.0.egg-info
rospkg_modules-1.4.0.egg-info
$ sudo pip3 install rospkg catkin-tools
Requirement already satisfied: rospkg in /usr/lib/python3/dist-packages (1.4.0)
Requirement already satisfied: catkin-tools in /usr/lib/python3/dist-packages (0.9.0)
```

**Comment by taketwo** [comment]
What about `$ nvim -c "py import rospkg"`. Does this show error messages?

**Comment by dongdongbh** [comment]
> nvim -c "py import rospkg"

no error

**Comment by dongdongbh** [comment]
> What about `$ nvim -c "py import rospkg"`. Does this show error messages?

No error.

**Comment by taketwo** [comment]
Strange. Your original error indicates that `vim` Python package is not available.

Do the following commands succeed?

* `$ nvim -c "python vim.command('echo \"test\"')"`
* `$ nvim -c "python import vim"`

**Comment by dongdongbh** [comment]
> Strange. Your original error indicates that `vim` Python package is not available.
> 
> Do the following commands succeed?
> 
> * `$ nvim -c "python vim.command('echo \"test\"')"`
> * `$ nvim -c "python import vim"`

`$ nvim -c "python vim.command('echo \"test\"')"`
```
Error detected while processing command line..function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined
```
`$ nvim -c "python import vim"`
no error.

**Comment by taketwo** [comment]
Please try to change this line:

https://github.com/taketwo/vim-ros/blob/dd1cf9df82c8588bb9d28352f82002647a354306/plugin/ros.vim#L31

to:

```viml
 exec g:_rpy "try: import vim, rospkg\nexcept ImportError: vim.command('let s:rospkg_not_found = 1')" 
```

**Comment by dongdongbh** [comment]
> 

After doing that, the error gone.

**Comment by dongdongbh** [comment]
> Please try to change this line:
> 
> https://github.com/taketwo/vim-ros/blob/dd1cf9df82c8588bb9d28352f82002647a354306/plugin/ros.vim#L31
> 
> to:
> 
> ```viml
>  exec g:_rpy "try: import vim, rospkg\nexcept ImportError: vim.command('let s:rospkg_not_found = 1')" 
> ```


After doing that, the error gone.

**Comment by taketwo** [comment]
Great. I'll push this fix to `master` later this week. In the meantime you can continue to use the plugin with modified code.

**Comment by taketwo** [comment]
Fixed is the master branch.
